export const northernDogs = [
"Alaskan Malamute",
"Pies grenlandzki",
"Samojed",
"Siberian Husky",
"Elkhund szary",
"Elkhund czarny",
"Jämthund",
"Karelski pies na niedźwiedzie",
"Łajka rosyjsko-europejska",
"Łajka wschodnioeuropejska",
"Łajka zachodnioeuropejska",
"Szpic nordycki",
"Norsk Lundenhund",
"Szpic fiński",
"Irlandzki szpic pasterski",
"Lapinporokoira",
"Norsk Buhund",
"Suomenlapinkoira (Fiński lapphund)",
"Svensk Lapphund",
"Vasgotaspets"
];
